### PR TITLE
Redirect log messages

### PR DESCRIPTION
**Pull request by jasonmhite**
PR for issue #4

### CODE REVIEW

**Comment by acockburn** [comment]
Thanks - it would be nice if you could update the docs as well

**Comment by jasonmhite** [comment]
OK, I added to `README.md`.

One question though, would you like me to add handling code to make calling `--daemonize`  with `logfile = STDOUT` or `logfile = STDERR` raise an exception? Current behavior is that it would write to a file named STDOUT and/or STDERR since I specifically did not mess with the `--daemonize` code path.

**Comment by acockburn** [comment]
Yes, I think the exception is a good idea - thanks for the README changes.

**Comment by jasonmhite** [comment]
Alright! I added a `ValueError` exception if you try and run in daemon mode with either redirect set in the config file.

Let me know if you want any other changes, otherwise I think it should be OK?

**Comment by jasonmhite** [comment]
Also not related, but I really like this project!

**Comment by acockburn** [comment]
Thanks a lot for your work, and glad that you like it :)

**Pull request merged**
