### PR TITLE
Add select value to update input_sliders

### PR DESCRIPTION
**Pull request by djbanks**
Allow an input_slider to have its value updated from the app api.

### CODE REVIEW

**Comment by acockburn** [comment]
Thanks for this - can you add an entry to the API doc as well please?

**Comment by djbanks** [comment]
I have added an entry in the API doc. Hopefully it is acceptable.

**Comment by acockburn** [comment]
Perfect thanks!

I am working on a new version - I still need a few days of testing as I have made some major changes to the scheduler but I will include this - hopefully you should see it next weekend.

**Comment by acockburn** [comment]
Merged manually - will be in 1.3.1

**Pull request closed without merging**
